module;

// clang-format off
// generated by ./scripts/sqlpp26-ddl2cpp --path-to-ddl tests/include/sqlpp26/tests/sqlite3/tables.sql --path-to-module tests/sqlite3/modules/sqlpp26.test.sqlite3.tables.cppm --namespace test --assume-auto-id --module-name sqlpp26.test.sqlite3.tables --generate-table-creation-helper

#include <optional>

export module sqlpp26.test.sqlite3.tables;

import sqlpp26.core;

namespace test {
export template<typename Db>
void create_tab_foo(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_foo
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text_nn_d varchar(255) NOT NULL DEFAULT '',
  int_n bigint,
  double_n double precision,
  u_int_n bigint UNSIGNED,
  bool_n bool,
  blob_n blob
))+++");
}

struct tab_foo_ {
  using generator = ::sqlpp::table_generator<tab_foo_, "tab_foo",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_nn_d", ::std::string_view>::with_default,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>,
    ::sqlpp::column_spec<"double_n", std::optional<double>>,
    ::sqlpp::column_spec<"u_int_n", std::optional<::std::uint64_t>>,
    ::sqlpp::column_spec<"bool_n", std::optional<bool>>,
    ::sqlpp::column_spec<"blob_n", std::optional<::std::span<uint8_t>>>>;
};
export using tab_foo = ::sqlpp::table<tab_foo_>;

export template<typename Db>
void create_tab_bar(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_bar
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text_n varchar(255) NULL,
  bool_nn bool NOT NULL DEFAULT false,
  int_n int
))+++");
}

struct tab_bar_ {
  using generator = ::sqlpp::table_generator<tab_bar_, "tab_bar",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_n", std::optional<::std::string_view>>,
    ::sqlpp::column_spec<"bool_nn", bool>::with_default,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>>;
};
export using tab_bar = ::sqlpp::table<tab_bar_>;

export template<typename Db>
void create_tab_date_time(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_date_time (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date_n date,
  timestamp_n datetime(3),
  date_timestamp_n_d datetime DEFAULT CURRENT_TIMESTAMP,
  time_n time(3)
))+++");
}

struct tab_date_time_ {
  using generator = ::sqlpp::table_generator<tab_date_time_, "tab_date_time",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"date_n", std::optional<::std::chrono::sys_days>>,
    ::sqlpp::column_spec<"timestamp_n", std::optional<::sqlpp::chrono::sys_microseconds>>,
    ::sqlpp::column_spec<"date_timestamp_n_d", std::optional<::sqlpp::chrono::sys_microseconds>>,
    ::sqlpp::column_spec<"time_n", std::optional<::std::chrono::microseconds>>>;
};
export using tab_date_time = ::sqlpp::table<tab_date_time_>;

export template<typename Db>
void create_tab_department(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_department (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name CHAR(100),
  division VARCHAR(255) NOT NULL DEFAULT 'engineering'
))+++");
}

struct tab_department_ {
  using generator = ::sqlpp::table_generator<tab_department_, "tab_department",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"name", std::optional<::std::string_view>>,
    ::sqlpp::column_spec<"division", ::std::string_view>::with_default>;
};
export using tab_department = ::sqlpp::table<tab_department_>;


} // namespace test
