module;

// clang-format off
// generated by ./scripts/sqlpp23-ddl2cpp --path-to-ddl tests/include/sqlpp23/tests/sqlite3/tables.sql --path-to-module tests/sqlite3/modules/sqlpp23.test.sqlite3.tables.cppm --namespace test --assume-auto-id --module-name sqlpp23.test.sqlite3.tables --generate-table-creation-helper

#include <optional>

#include <sqlpp23/core/name/create_name_tag.h>

import sqlpp23.core;

export module sqlpp23.test.sqlite3.tables;

namespace test {
  export template<typename Db>
  void createTabFoo(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS tab_foo)+++");
    db(R"+++(CREATE TABLE tab_foo
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text_nn_d varchar(255) NOT NULL DEFAULT '',
  int_n bigint,
  double_n double precision,
  u_int_n bigint UNSIGNED,
  bool_n bool,
  blob_n blob
))+++");
  }

  export struct TabFoo_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct TextNnD {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(text_nn_d, textNnD);
      using data_type = ::sqlpp::text;
      using has_default = std::true_type;
    };
    struct IntN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(int_n, intN);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    struct DoubleN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(double_n, doubleN);
      using data_type = std::optional<::sqlpp::floating_point>;
      using has_default = std::true_type;
    };
    struct UIntN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(u_int_n, uIntN);
      using data_type = std::optional<::sqlpp::unsigned_integral>;
      using has_default = std::true_type;
    };
    struct BoolN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(bool_n, boolN);
      using data_type = std::optional<::sqlpp::boolean>;
      using has_default = std::true_type;
    };
    struct BlobN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(blob_n, blobN);
      using data_type = std::optional<::sqlpp::blob>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(tab_foo, tabFoo);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               TextNnD,
               IntN,
               DoubleN,
               UIntN,
               BoolN,
               BlobN>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  export using TabFoo = ::sqlpp::table_t<TabFoo_>;

  export template<typename Db>
  void createTabBar(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS tab_bar)+++");
    db(R"+++(CREATE TABLE tab_bar
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text_n varchar(255) NULL,
  bool_nn bool NOT NULL DEFAULT false,
  int_n int
))+++");
  }

  export struct TabBar_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct TextN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(text_n, textN);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct BoolNn {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(bool_nn, boolNn);
      using data_type = ::sqlpp::boolean;
      using has_default = std::true_type;
    };
    struct IntN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(int_n, intN);
      using data_type = std::optional<::sqlpp::integral>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(tab_bar, tabBar);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               TextN,
               BoolNn,
               IntN>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  export using TabBar = ::sqlpp::table_t<TabBar_>;

  export template<typename Db>
  void createTabDateTime(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS tab_date_time)+++");
    db(R"+++(CREATE TABLE tab_date_time (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date_n date,
  timestamp_n datetime(3),
  date_timestamp_n_d datetime DEFAULT CURRENT_TIMESTAMP,
  time_n time(3)
))+++");
  }

  export struct TabDateTime_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct DateN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(date_n, dateN);
      using data_type = std::optional<::sqlpp::date>;
      using has_default = std::true_type;
    };
    struct TimestampN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(timestamp_n, timestampN);
      using data_type = std::optional<::sqlpp::timestamp>;
      using has_default = std::true_type;
    };
    struct DateTimestampND {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(date_timestamp_n_d, dateTimestampND);
      using data_type = std::optional<::sqlpp::timestamp>;
      using has_default = std::true_type;
    };
    struct TimeN {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(time_n, timeN);
      using data_type = std::optional<::sqlpp::time>;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(tab_date_time, tabDateTime);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               DateN,
               TimestampN,
               DateTimestampND,
               TimeN>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  export using TabDateTime = ::sqlpp::table_t<TabDateTime_>;

  export template<typename Db>
  void createTabDepartment(Db& db) {
    db(R"+++(DROP TABLE IF EXISTS tab_department)+++");
    db(R"+++(CREATE TABLE tab_department (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name CHAR(100),
  division VARCHAR(255) NOT NULL DEFAULT 'engineering'
))+++");
  }

  export struct TabDepartment_ {
    struct Id {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
      using data_type = ::sqlpp::integral;
      using has_default = std::true_type;
    };
    struct Name {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(name, name);
      using data_type = std::optional<::sqlpp::text>;
      using has_default = std::true_type;
    };
    struct Division {
      SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(division, division);
      using data_type = ::sqlpp::text;
      using has_default = std::true_type;
    };
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(tab_department, tabDepartment);
    template<typename T>
    using _table_columns = sqlpp::table_columns<T,
               Id,
               Name,
               Division>;
    using _required_insert_columns = sqlpp::detail::type_set<>;
  };
  export using TabDepartment = ::sqlpp::table_t<TabDepartment_>;

} // namespace test
