#pragma once

// clang-format off
// generated by ./scripts/sqlpp26-ddl2cpp --path-to-ddl tests/include/sqlpp26/tests/core/tables.sql --path-to-header tests/include/sqlpp26/tests/core/tables.h --namespace test --assume-auto-id --generate-table-creation-helper


#include <optional>


#include <sqlpp26/core/basic/table.h>

namespace test {
template<typename Db>
void createTabFoo(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_foo
(
	id BIGSERIAL PRIMARY KEY,
	text_nn_d varchar(255) NOT NULL DEFAULT "",
	int_n bigint,
        int_c_n bigint GENERATED ALWAYS AS (int_n * 2) STORED,
	double_n double,
	u_int_n bigint UNSIGNED,
	blob_n BLOB,
        bool_n bool
))+++");
}

struct TabFoo_ {
  using generator = ::sqlpp::make_table<TabFoo_, "tab_foo",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"textNnD", ::std::string_view>::with_default::with_sql_name<"text_nn_d">,
    ::sqlpp::column_spec<"intN", std::optional<::std::int64_t>>::with_default::with_sql_name<"int_n">,
    ::sqlpp::column_spec<"intCN", const std::optional<::std::int64_t>>::with_default::with_sql_name<"int_c_n">,
    ::sqlpp::column_spec<"doubleN", std::optional<double>>::with_default::with_sql_name<"double_n">,
    ::sqlpp::column_spec<"uIntN", std::optional<::std::uint64_t>>::with_default::with_sql_name<"u_int_n">,
    ::sqlpp::column_spec<"blobN", std::optional<::std::span<const uint8_t>>>::with_default::with_sql_name<"blob_n">,
    ::sqlpp::column_spec<"boolN", std::optional<bool>>::with_default::with_sql_name<"bool_n">>;
};
using TabFoo = ::sqlpp::table<TabFoo_>;

template<typename Db>
void createTabBar(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_bar
(
	id bigint AUTO_INCREMENT PRIMARY KEY,
	text_n varchar(255) NULL DEFAULT "",
	bool_nn bool NOT NULL,
	int_n int
))+++");
}

struct TabBar_ {
  using generator = ::sqlpp::make_table<TabBar_, "tab_bar",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"textN", std::optional<::std::string_view>>::with_default::with_sql_name<"text_n">,
    ::sqlpp::column_spec<"boolNn", bool>::with_sql_name<"bool_nn">,
    ::sqlpp::column_spec<"intN", std::optional<::std::int64_t>>::with_default::with_sql_name<"int_n">>;
};
using TabBar = ::sqlpp::table<TabBar_>;

template<typename Db>
void createTabDateTime(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_date_time
(
	id bigint AUTO_INCREMENT PRIMARY KEY,
	date_n date,
	timestamp_n datetime,
	time_n time
))+++");
}

struct TabDateTime_ {
  using generator = ::sqlpp::make_table<TabDateTime_, "tab_date_time",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"dateN", std::optional<::std::chrono::sys_days>>::with_default::with_sql_name<"date_n">,
    ::sqlpp::column_spec<"timestampN", std::optional<std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds>>>::with_default::with_sql_name<"timestamp_n">,
    ::sqlpp::column_spec<"timeN", std::optional<::std::chrono::microseconds>>::with_default::with_sql_name<"time_n">>;
};
using TabDateTime = ::sqlpp::table<TabDateTime_>;


} // namespace test
