#pragma once

// clang-format off
// generated by ./scripts/sqlpp26-ddl2cpp --path-to-ddl tests/include/sqlpp26/tests/core/tables.sql --path-to-header tests/include/sqlpp26/tests/core/tables.h --namespace test --assume-auto-id --generate-table-creation-helper


#include <optional>


#include <sqlpp26/core/basic/table.h>

namespace test {
template<typename Db>
void create_tab_foo(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_foo
(
  id BIGSERIAL PRIMARY KEY,
  text_nn_d varchar(255) NOT NULL DEFAULT "",
  int_n bigint,
  int_c_n bigint GENERATED ALWAYS AS (int_n * 2) STORED,
  -- cpp_name:float_n
  double_n double,
  u_int_n bigint UNSIGNED,
  blob_n BLOB,
  bool_n bool
))+++");
}

struct tab_foo_ {
  using generator = ::sqlpp::table_generator<tab_foo_, "tab_foo",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_nn_d", ::std::string_view>::with_default,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>,
    ::sqlpp::column_spec<"int_c_n", const std::optional<::std::int64_t>>,
    ::sqlpp::column_spec<"double_n", std::optional<double>>::with_cpp_name<"float_n">,
    ::sqlpp::column_spec<"u_int_n", std::optional<::std::uint64_t>>,
    ::sqlpp::column_spec<"blob_n", std::optional<::std::span<uint8_t>>>,
    ::sqlpp::column_spec<"bool_n", std::optional<bool>>>;
};
using tab_foo = ::sqlpp::table<tab_foo_>;

template<typename Db>
void create_tab_bar(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_bar
(
    id bigint AUTO_INCREMENT PRIMARY KEY,
    text_n varchar(255) NULL DEFAULT "",
    bool_nn bool NOT NULL,
    int_n int
))+++");
}

struct tab_bar_ {
  using generator = ::sqlpp::table_generator<tab_bar_, "tab_bar",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_n", std::optional<::std::string_view>>,
    ::sqlpp::column_spec<"bool_nn", bool>,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>>;
};
using tab_bar = ::sqlpp::table<tab_bar_>;

template<typename Db>
void create_tab_date_time(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_date_time
(
    id bigint AUTO_INCREMENT PRIMARY KEY,
    date_n date,
    timestamp_n datetime,
    time_n time
))+++");
}

struct tab_date_time_ {
  using generator = ::sqlpp::table_generator<tab_date_time_, "tab_date_time",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"date_n", std::optional<::std::chrono::sys_days>>,
    ::sqlpp::column_spec<"timestamp_n", std::optional<::sqlpp::chrono::sys_microseconds>>,
    ::sqlpp::column_spec<"time_n", std::optional<::std::chrono::microseconds>>>;
};
using tab_date_time = ::sqlpp::table<tab_date_time_>;


} // namespace test
