#pragma once

// clang-format off
// generated by ./scripts/sqlpp26-ddl2cpp --path-to-ddl tests/include/sqlpp26/tests/mysql/tables.sql --path-to-header tests/include/sqlpp26/tests/mysql/tables-using-modules.h --namespace test --assume-auto-id --use-import-sqlpp26 --generate-table-creation-helper


#include <optional>

import sqlpp26.core;


namespace test {
template<typename Db>
void create_tab_foo(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_foo
(
  id bigint(20) AUTO_INCREMENT PRIMARY KEY,
  text_nn_d varchar(255) NOT NULL DEFAULT '',
  int_n bigint,
  double_n double precision,
  u_int_n bigint UNSIGNED,
  bool_n bool,
  blob_n blob
))+++");
}

struct tab_foo_ {
  using generator = ::sqlpp::table_generator<tab_foo_, "tab_foo",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_nn_d", ::std::string_view>::with_default,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>::with_default,
    ::sqlpp::column_spec<"double_n", std::optional<double>>::with_default,
    ::sqlpp::column_spec<"u_int_n", std::optional<::std::uint64_t>>::with_default,
    ::sqlpp::column_spec<"bool_n", std::optional<bool>>::with_default,
    ::sqlpp::column_spec<"blob_n", std::optional<::std::span<const uint8_t>>>::with_default>;
};
using tab_foo = ::sqlpp::table<tab_foo_>;

template<typename Db>
void create_tab_bar(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_bar
(
  id bigint(20) AUTO_INCREMENT PRIMARY KEY,
  text_n varchar(255) NULL,
  bool_nn bool NOT NULL DEFAULT false,
  int_n int
))+++");
}

struct tab_bar_ {
  using generator = ::sqlpp::table_generator<tab_bar_, "tab_bar",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_n", std::optional<::std::string_view>>::with_default,
    ::sqlpp::column_spec<"bool_nn", bool>::with_default,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>::with_default>;
};
using tab_bar = ::sqlpp::table<tab_bar_>;

template<typename Db>
void create_tab_date_time(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_date_time (
  id bigint(20) AUTO_INCREMENT PRIMARY KEY,
  date_n date,
  timestamp_n datetime(3),
  date_timestamp_n_d datetime DEFAULT CURRENT_TIMESTAMP,
  time_n time(3)
))+++");
}

struct tab_date_time_ {
  using generator = ::sqlpp::table_generator<tab_date_time_, "tab_date_time",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"date_n", std::optional<::std::chrono::sys_days>>::with_default,
    ::sqlpp::column_spec<"timestamp_n", std::optional<std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds>>>::with_default,
    ::sqlpp::column_spec<"date_timestamp_n_d", std::optional<std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds>>>::with_default,
    ::sqlpp::column_spec<"time_n", std::optional<::std::chrono::microseconds>>::with_default>;
};
using tab_date_time = ::sqlpp::table<tab_date_time_>;

template<typename Db>
void create_tab_json(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_json (
  id bigint(20) AUTO_INCREMENT PRIMARY KEY,
  data JSON NOT NULL
))+++");
}

struct tab_json_ {
  using generator = ::sqlpp::table_generator<tab_json_, "tab_json",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"data", ::std::string_view>>;
};
using tab_json = ::sqlpp::table<tab_json_>;

template<typename Db>
void create_tab_department(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_department (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name CHAR(100),
  division VARCHAR(255) NOT NULL DEFAULT 'engineering'
))+++");
}

struct tab_department_ {
  using generator = ::sqlpp::table_generator<tab_department_, "tab_department",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"name", std::optional<::std::string_view>>::with_default,
    ::sqlpp::column_spec<"division", ::std::string_view>::with_default>;
};
using tab_department = ::sqlpp::table<tab_department_>;


} // namespace test
