#pragma once

/*
 * Copyright (c) 2026, Matthijs Möhlmann
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <cstdint>

#include <sqlpp23/core/type_traits.h>

// ---------------------------------------------------------------------------
// PointId — strong typedef over int64_t for the tab_point primary key.
//
// Prevents accidental mixing of ids from different tables at compile time.
// The underlying value is a bigserial generated by PostgreSQL, so PointId
// has has_default = true_type in the table spec and is never provided on
// INSERT.
// ---------------------------------------------------------------------------

struct PointId {
  int64_t value;
  bool operator==(const PointId&) const = default;
};

// Predicate: matches any expression whose data type is PointId.
template <typename T>
struct is_point_id : public std::is_same<sqlpp::data_type_of_t<T>, PointId> {};
template <typename T>
inline constexpr bool is_point_id_v = is_point_id<T>::value;

// Serialize PointId to SQL by delegating to the int64_t overload.
template <typename Context>
auto to_sql_string(Context& context, const PointId& id) {
  using sqlpp::to_sql_string;
  return to_sql_string(context, id.value);
}

// Read a PointId from a result row field by delegating to int64_t.
template <typename Result>
void read_field(const Result& result, size_t field_index, PointId& id) {
  read_field(result, field_index, id.value);
}

// Bind a PointId as a prepared statement parameter by delegating to int64_t.
template <typename Statement>
void bind_parameter(Statement& stmt, size_t index, const PointId& id) {
  bind_parameter(stmt, index, id.value);
}

// ---------------------------------------------------------------------------
// namespace sqlpp — type system glue
// ---------------------------------------------------------------------------

namespace sqlpp {

// PointId is its own data type tag, giving it a distinct identity from plain
// sqlpp::integral and from any other strong id type.
template <>
struct data_type_of<PointId> {
  using type = PointId;
};

// Result rows hold PointId directly.
template <>
struct result_data_type_of<PointId> {
  using type = PointId;
};

// Prepared statement parameter structs hold PointId directly.
template <>
struct parameter_value<PointId> {
  using type = PointId;
};

// Only PointId can be assigned to a PointId column (SET / INSERT).
template <typename L, typename R>
  requires(is_point_id_v<L> and is_point_id_v<R>)
struct values_are_assignable<L, R> : public std::true_type {};

// Only PointId can be compared to a PointId column (WHERE, ORDER BY).
template <typename L, typename R>
  requires(is_point_id_v<L> and is_point_id_v<R>)
struct values_are_comparable<L, R> : public std::true_type {};

}  // namespace sqlpp
