#pragma once

/*
 * Copyright (c) 2026, Matthijs Möhlmann
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *  * Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <sqlpp23/core/basic/table.h>
#include <sqlpp23/core/basic/table_columns.h>
#include <sqlpp23/core/name/create_name_tag.h>
#include <sqlpp23/core/type_traits.h>

#include "color.h"
#include "point_id.h"

// ---------------------------------------------------------------------------
// TabPoint — table definition
//
// ddl2cpp only emits built-in sqlpp23 tags (integral, text, …) and cannot
// generate custom C++ types as a column's data_type. The column specs are
// therefore written by hand; only the data_type lines differ from what
// ddl2cpp would produce for a plain bigserial / enum column.
// ---------------------------------------------------------------------------

namespace test {

struct TabPoint_ {
  struct Id {
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(id, id);
    using data_type = PointId;           // strong typedef over bigserial
    using has_default = std::true_type;  // generated by PostgreSQL on INSERT
  };
  struct Color_ {
    SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(color, color);
    using data_type = Color;              // C++ enum <-> PostgreSQL ENUM
    using has_default = std::false_type;  // required on INSERT
  };
  SQLPP_CREATE_NAME_TAG_FOR_SQL_AND_CPP(tab_point, tabPoint);
  template <typename T>
  using _table_columns = sqlpp::table_columns<T, Id, Color_>;
  using _required_insert_columns = sqlpp::detail::type_set<
      sqlpp::column_t<sqlpp::table_t<TabPoint_>, Color_>>;
};
using TabPoint = ::sqlpp::table_t<TabPoint_>;

// Creates (or recreates) the tab_point table and its color_enum type.
// Drops both in the correct dependency order first so the function is
// idempotent across test runs.
template <typename Db>
void createTabPoint(Db& db) {
  db("DROP TABLE IF EXISTS tab_point");
  db("DROP TYPE IF EXISTS color_enum");
  db("CREATE TYPE color_enum AS ENUM ('red', 'green', 'blue')");
  db(R"+++(CREATE TABLE tab_point
(
  id    bigserial  PRIMARY KEY,
  color color_enum NOT NULL
))+++");
}

}  // namespace test
