module;

// clang-format off
// generated by ./scripts/sqlpp26-ddl2cpp --path-to-ddl tests/include/sqlpp26/tests/core/tables.sql --path-to-module tests/core/modules/sqlpp26.test.core.tables.cppm --module-name=sqlpp26.test.core.tables --namespace test --assume-auto-id

#include <optional>

export module sqlpp26.test.core.tables;

import sqlpp26.core;

namespace test {
struct TabFoo_ {
  using generator = ::sqlpp::make_table<TabFoo_, "tab_foo",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"textNnD", ::std::string_view>::with_default::with_sql_name<"text_nn_d">,
    ::sqlpp::column_spec<"intN", std::optional<::std::int64_t>>::with_default::with_sql_name<"int_n">,
    ::sqlpp::column_spec<"intCN", const std::optional<::std::int64_t>>::with_default::with_sql_name<"int_c_n">,
    ::sqlpp::column_spec<"doubleN", std::optional<double>>::with_default::with_sql_name<"double_n">,
    ::sqlpp::column_spec<"uIntN", std::optional<::std::uint64_t>>::with_default::with_sql_name<"u_int_n">,
    ::sqlpp::column_spec<"blobN", std::optional<::std::span<const uint8_t>>>::with_default::with_sql_name<"blob_n">,
    ::sqlpp::column_spec<"boolN", std::optional<bool>>::with_default::with_sql_name<"bool_n">>;
};
export using TabFoo = ::sqlpp::table<TabFoo_>;

struct TabBar_ {
  using generator = ::sqlpp::make_table<TabBar_, "tab_bar",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"textN", std::optional<::std::string_view>>::with_default::with_sql_name<"text_n">,
    ::sqlpp::column_spec<"boolNn", bool>::with_sql_name<"bool_nn">,
    ::sqlpp::column_spec<"intN", std::optional<::std::int64_t>>::with_default::with_sql_name<"int_n">>;
};
export using TabBar = ::sqlpp::table<TabBar_>;

struct TabDateTime_ {
  using generator = ::sqlpp::make_table<TabDateTime_, "tab_date_time",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"dateN", std::optional<::std::chrono::sys_days>>::with_default::with_sql_name<"date_n">,
    ::sqlpp::column_spec<"timestampN", std::optional<std::chrono::time_point<std::chrono::system_clock, std::chrono::microseconds>>>::with_default::with_sql_name<"timestamp_n">,
    ::sqlpp::column_spec<"timeN", std::optional<::std::chrono::microseconds>>::with_default::with_sql_name<"time_n">>;
};
export using TabDateTime = ::sqlpp::table<TabDateTime_>;


} // namespace test
