module;

// clang-format off
// generated by ./scripts/sqlpp26-ddl2cpp --path-to-ddl tests/include/sqlpp26/tests/core/tables.sql --path-to-module tests/core/modules/sqlpp26.test.core.tables.cppm --module-name=sqlpp26.test.core.tables --namespace test --assume-auto-id

#include <optional>

export module sqlpp26.test.core.tables;

import sqlpp26.core;

namespace test {
struct tab_foo_ {
  using generator = ::sqlpp::table_generator<tab_foo_, "tab_foo",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_nn_d", ::std::string_view>::with_default,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>,
    ::sqlpp::column_spec<"int_c_n", const std::optional<::std::int64_t>>,
    ::sqlpp::column_spec<"double_n", std::optional<double>>::with_cpp_name<"float_n">,
    ::sqlpp::column_spec<"u_int_n", std::optional<::std::uint64_t>>,
    ::sqlpp::column_spec<"blob_n", std::optional<::std::span<uint8_t>>>,
    ::sqlpp::column_spec<"bool_n", std::optional<bool>>>;
};
export using tab_foo = ::sqlpp::table<tab_foo_>;

struct tab_bar_ {
  using generator = ::sqlpp::table_generator<tab_bar_, "tab_bar",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_n", std::optional<::std::string_view>>,
    ::sqlpp::column_spec<"bool_nn", bool>,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>>;
};
export using tab_bar = ::sqlpp::table<tab_bar_>;

struct tab_date_time_ {
  using generator = ::sqlpp::table_generator<tab_date_time_, "tab_date_time",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"date_n", std::optional<::std::chrono::sys_days>>,
    ::sqlpp::column_spec<"timestamp_n", std::optional<::sqlpp::chrono::sys_microseconds>>,
    ::sqlpp::column_spec<"time_n", std::optional<::std::chrono::microseconds>>>;
};
export using tab_date_time = ::sqlpp::table<tab_date_time_>;


} // namespace test
