#pragma once

// clang-format off
// generated by ./scripts/sqlpp26-ddl2cpp --path-to-ddl tests/postgresql/recipes/enum/db_model.sql --path-to-header tests/postgresql/recipes/enum/db_model.h --namespace test --assume-auto-id --generate-table-creation-helper


#include <optional>


#include <sqlpp26/core/basic/table.h>

namespace test {
template<typename Db>
void create_tab_enums(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_enums (
  -- cpp_type:animal
  animal bigint,
  -- cpp_type:shape
  cage shape
))+++");
}

struct tab_enums_ {
  using generator = ::sqlpp::table_generator<tab_enums_, "tab_enums",
    ::sqlpp::column_spec<"animal", std::optional<animal>>::with_default,
    ::sqlpp::column_spec<"cage", std::optional<shape>>::with_default>;
};
using tab_enums = ::sqlpp::table<tab_enums_>;


} // namespace test
