#pragma once

// clang-format off
// generated by ./scripts/sqlpp26-ddl2cpp --path-to-ddl tests/include/sqlpp26/tests/postgresql/tables.sql --path-to-header tests/include/sqlpp26/tests/postgresql/tables.h --namespace test --assume-auto-id --generate-table-creation-helper


#include <optional>


#include <sqlpp26/core/basic/table.h>

namespace test {
template<typename Db>
void create_tab_foo(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_foo
(
  id bigserial PRIMARY KEY,
  text_nn_d varchar(255) NOT NULL DEFAULT '',
  int_n bigint,
  double_n double precision,
  int_nn_u bigint UNIQUE,
  bool_n bool,
  blob_n bytea,
  UNIQUE(id, int_nn_u) -- to test multi-argument on_confict
))+++");
}

struct tab_foo_ {
  using generator = ::sqlpp::table_generator<tab_foo_, "tab_foo",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_nn_d", ::std::string_view>::with_default,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>,
    ::sqlpp::column_spec<"double_n", std::optional<double>>,
    ::sqlpp::column_spec<"int_nn_u", std::optional<::std::int64_t>>,
    ::sqlpp::column_spec<"bool_n", std::optional<bool>>,
    ::sqlpp::column_spec<"blob_n", std::optional<::std::span<uint8_t>>>>;
};
using tab_foo = ::sqlpp::table<tab_foo_>;

template<typename Db>
void create_tab_bar(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_bar
(
  id bigserial PRIMARY KEY,
  text_n varchar(255) NULL,
  bool_nn bool NOT NULL DEFAULT false,
  int_n int
))+++");
}

struct tab_bar_ {
  using generator = ::sqlpp::table_generator<tab_bar_, "tab_bar",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"text_n", std::optional<::std::string_view>>,
    ::sqlpp::column_spec<"bool_nn", bool>::with_default,
    ::sqlpp::column_spec<"int_n", std::optional<::std::int64_t>>>;
};
using tab_bar = ::sqlpp::table<tab_bar_>;

template<typename Db>
void create_tab_date_time(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_date_time
(
  date_n date,
  timestamp_n timestamp,
  time_n time,
  timestamp_n_tz timestamp with time zone,
  time_n_tz time with time zone
))+++");
}

struct tab_date_time_ {
  using generator = ::sqlpp::table_generator<tab_date_time_, "tab_date_time",
    ::sqlpp::column_spec<"date_n", std::optional<::std::chrono::sys_days>>,
    ::sqlpp::column_spec<"timestamp_n", std::optional<::sqlpp::chrono::sys_microseconds>>,
    ::sqlpp::column_spec<"time_n", std::optional<::std::chrono::microseconds>>,
    ::sqlpp::column_spec<"timestamp_n_tz", std::optional<::sqlpp::chrono::sys_microseconds>>,
    ::sqlpp::column_spec<"time_n_tz", std::optional<::std::chrono::microseconds>>>;
};
using tab_date_time = ::sqlpp::table<tab_date_time_>;

template<typename Db>
void create_blob_sample(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE blob_sample (
  id bigserial PRIMARY KEY,
  data bytea
))+++");
}

struct blob_sample_ {
  using generator = ::sqlpp::table_generator<blob_sample_, "blob_sample",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"data", std::optional<::std::span<uint8_t>>>>;
};
using blob_sample = ::sqlpp::table<blob_sample_>;

template<typename Db>
void create_tab_except(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_except (
  int_small_n_u smallint UNIQUE,
  text_short_n text CHECK( length(text_short_n) < 5 )
))+++");
}

struct tab_except_ {
  using generator = ::sqlpp::table_generator<tab_except_, "tab_except",
    ::sqlpp::column_spec<"int_small_n_u", std::optional<::std::int64_t>>,
    ::sqlpp::column_spec<"text_short_n", std::optional<::std::string_view>>>;
};
using tab_except = ::sqlpp::table<tab_except_>;

template<typename Db>
void create_tab_department(Db& db) {
  db(R"+++(DROP TABLE IF EXISTS {table.name})+++");
  db(R"+++(CREATE TABLE tab_department (
  id SERIAL PRIMARY KEY,
  name CHAR(100),
  division VARCHAR(255) NOT NULL DEFAULT 'engineering'
))+++");
}

struct tab_department_ {
  using generator = ::sqlpp::table_generator<tab_department_, "tab_department",
    ::sqlpp::column_spec<"id", ::std::int64_t>::with_default,
    ::sqlpp::column_spec<"name", std::optional<::std::string_view>>,
    ::sqlpp::column_spec<"division", ::std::string_view>::with_default>;
};
using tab_department = ::sqlpp::table<tab_department_>;


} // namespace test
